name: Deploy

on: [push]

jobs:
  build:

    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i --delete"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: "/home/${{ secrets.REMOTE_USER }}/app"
        EXCLUDE: ".git/*,.github/*,.gitignore"
        SCRIPT_BEFORE: |
          whoami
          ls -al
          sudo docker ps -q --filter "name=bot" | xargs -r sudo docker stop
        SCRIPT_AFTER: |
          whoami
          ls -al
          cd /home/${{ secrets.REMOTE_USER }}/app
          echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} > .env
          sudo docker build -t weather_bot .
          sudo docker rmi $(sudo docker images -f "dangling=true" -q)
          sudo docker run -d --rm --name wb weather_bot
